import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileExists, writeText } from './fs.js';
import { buildCommand, type PackageManager } from './detect.js';

export interface CiOptions {
  cwd: string;
  packageManager: PackageManager;
  nodeVersion?: string;
  buildOutputDir?: string;
}

const DEFAULT_NODE_VERSION = '22';

function getSetupAction(pm: PackageManager, cwd: string): { install: string; cache?: string } {
  switch (pm) {
    case 'pnpm':
      return { install: 'pnpm install --frozen-lockfile', cache: 'pnpm' };
    case 'yarn':
      return { install: 'yarn install --frozen-lockfile', cache: 'yarn' };
    case 'bun':
      return { install: 'bun install --frozen-lockfile' };
    default:
      return {
        install: existsSync(join(cwd, 'package-lock.json')) ? 'npm ci' : 'npm install',
      };
  }
}

function getSetupNodeCache(pm: PackageManager, cwd: string): string {
  const { cache } = getSetupAction(pm, cwd);
  if (!cache) return '';
  return `\n          cache: '${cache}'`;
}

function getPnpmSetupStep(pm: PackageManager): string {
  if (pm !== 'pnpm') return '';
  return `
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
`;
}

export function generateWorkflow(options: CiOptions): string {
  const nodeVersion = options.nodeVersion ?? DEFAULT_NODE_VERSION;
  const outDir = options.buildOutputDir ?? 'dist';
  const { install } = getSetupAction(options.packageManager, options.cwd);
  const cacheLine = getSetupNodeCache(options.packageManager, options.cwd);
  const build = buildCommand(options.packageManager);

  return `# Generated by vite-on-github — deploys Vite app to GitHub Pages
name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
${getPnpmSetupStep(options.packageManager)}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'${cacheLine}

      - name: Install dependencies
        run: ${install}

      - name: Build
        run: ${build}

      - name: SPA fallback for client-side routing
        run: cp ${outDir}/index.html ${outDir}/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${outDir}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`;
}

export function writeWorkflow(options: CiOptions): { path: string; created: boolean } {
  const workflowPath = join(options.cwd, '.github', 'workflows', 'deploy.yml');
  const exists = fileExists(workflowPath);
  writeText(workflowPath, generateWorkflow(options));
  return { path: workflowPath, created: !exists };
}
