export { init, printSummary } from './commands/init.js';
export { detectProject, detectPackageManager } from './utils/detect.js';
export { detectGitRemote } from './utils/git.js';
export { patchViteConfig, createDefaultViteConfig } from './utils/vite-config.js';
export { patchRouterFiles } from './utils/router.js';
export { writeWorkflow, generateWorkflow } from './utils/ci.js';
export type { InitOptions, InitResult } from './types.js';
export type { ProjectInfo, PackageManager, Framework } from './utils/detect.js';
export type { GitRemoteInfo } from './utils/git.js';
export type { CiOptions } from './utils/ci.js';
